sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project complex-k8s-268018
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials complex-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sandeshkumar/temp-tag -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandeshkumar/temp-tag npm run test

deploy:
  # No default provider for deployment to kubernetes by travis. Doing it from scratch
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
